"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FileSorter.py']
DATA_FILES = ['pic.icns']
OPTIONS = {'iconfile': '/Users/deftone/sources/PycharmProjects/file_sort/pic.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
